_target_: lightning.pytorch.trainer.trainer.Trainer

defaults:
  - /logger: tensorboard

max_epochs: 100
accelerator: auto
devices: auto
precision: 16-mixed
gradient_clip_val: true
enable_progress_bar: true
