_target_: cnn_study.models.lenet.LeNet5

input_channels: 1
num_classes: ${num_classes}
activation: relu # relu, sigmoid, or tanh
pooling: avg # avg or max
use_bn: false # set to batch normalization
classifier_type: conv_dense
